# -*- coding: utf-8 -*-
"""Project 1 - Carbon Footprint From Food

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvzLezN94VK5-0EZlrIxPPpp9ZbGFeQ8
"""

# Step 1: Define the CO2e emissions(in kg CO2e per kg of food) for different food categories
co2e_per_kg = {
    "beef":27.0,
    "chicken":6.9,
    "fish":3.0,
    "eggs":4.5,
    "milk":1.0,
    "rice":2.7,
    "wheat":1.4,
    "potatoes":1.2,
    "vegetables":0.2,
    "fruits":0.5,
}

# Step 2: Define a function to calculate the carbon footprint of a meal

def calculate_carbon_footprint(meal):
  total_co2e = 0.0
  for food, amount in meal.items():
    co2e=co2e_per_kg.get(food, 0.0) * amount/1000.0
    total_co2e += co2e
  return total_co2e

#Example meal with amounts in grams

meal= {
    "beef":200,
    "eggs":500,
    "potatoes":250,
    "fruits":450
}

# Step 3: Calculate the carbon footprint of the meal
carbon_footprint = calculate_carbon_footprint(meal)

# Step 4: Print the result
print(carbon_footprint)